version: '3.8'

services:
  neo4j:
    image: neo4j:5.17 # ou a versão desejada
    container_name: neo4j-server
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP interface
      - "7687:7687"   # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/StrongPass123 # username/senha
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
